chain = "polygon"
source = "rpc" # bigquery or rpc
pool_address = "0x9B08288C3Be4F62bbf8d1C20Ac9C5e6f9467d8B7"
save_path = "/home/sun/AA-labs-FE/code/demeter/data_rpc"

[big_query]
start = "2022-9-19"
end = "2022-9-20"
auth_file = "../auth/airy-sight-361003-d14b5ce41c48.json"

[rpc]
end_point="https://localhost:8545"
#auth_string = "Basic Y3J0Yzo3NKY3TjY"
proxy = "http://localhost:8080"
start_height = 30194000
end_height = 30232000
batch_size = 500
